[package]
name = "wasmcloud-api"
version = "0.1.0"
authors = ["Christine Dodrill <me@christine.website>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1", features = ["postgres", "r2d2", "uuidv07"] }
rocket = "0.4"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
log = "0"
uuid = { version = "0.7", features = ["serde", "v4"] }
rocket_oauth2 = "0.4"

[dependencies.rocket_contrib]
version = "0.4"
default-features = false
features = ["json", "diesel_postgres_pool", "uuid"]
